# Generated by Django 5.2.12 on 2026-03-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='coordinates',
            field=models.TextField(blank=True, help_text='SVG path data (d attribute)'),
        ),
        migrations.AddField(
            model_name='house',
            name='site',
            field=models.IntegerField(choices=[(1, 'Site 1'), (2, 'Site 2')], default=1),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_number',
            field=models.CharField(help_text='E.g. Block No. 1 | Lot No. 1', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='svg_id',
            field=models.CharField(help_text='Matches SVG element id, e.g. house-001', max_length=30, unique=True),
        ),
    ]
