# Generated by Django 5.2.12 on 2026-03-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_house_coordinates_house_site_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['site', 'house_number'], 'verbose_name': 'House', 'verbose_name_plural': 'Houses'},
        ),
        migrations.AlterField(
            model_name='house',
            name='house_number',
            field=models.CharField(help_text='E.g. Block No. 1 | Lot No. 1', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='house',
            unique_together={('site', 'house_number')},
        ),
    ]
