# Generated by Django 5.2.12 on 2026-03-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0008_uuid_primary_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='family_size',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Household size'),
        ),
    ]
