# Generated by Django 6.0.3 on 2026-03-14 00:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0009_alter_application_family_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendingArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_number', models.IntegerField(choices=[(1, 'Site 1'), (2, 'Site 2')], unique=True)),
                ('name', models.CharField(help_text='E.g. Brgy. Old Poblacion', max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sending Area',
                'verbose_name_plural': 'Sending Areas',
                'ordering': ['site_number'],
            },
        ),
    ]
